[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  command = "CI= npm run build"


[build]
  base = "frontend/"
  publish = "build/"
  command = "npm run build"


 [[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"