

name: ESLint CI


on:
  
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'


  workflow_dispatch:

jobs:

  eslint:
  
    runs-on: ubuntu-latest

    steps:
     
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Installing dependencies
        run: npm install
        
      - name: Running ESLint
        run: npm run lint
